### PR TITLE
python-libnmap - XML External Entity (XXE) Injection - Fix:

### PR DESCRIPTION
**Pull request by huntr-helper**
https://github.com/mufeedvh fixed the vulnerability associated with XML External Entity (XXE) Injection.
This fix is being submitted on behalf of https://github.com/mufeedvh - they have been awarded $25 for fixing the vulnerability through the huntr bug bounty program.
Think you could fix a vulnerability like this - get involved (https://huntr.dev).
Q | A
Version Affected | ALL
Bug Fix | YES
Further References | https://github.com/418sec/python-libnmap/pull/1
Relevant Issue | https://github.com/savon-noir/python-libnmap/issues/87

### CODE REVIEW

**Comment by JamieSlome** [comment]
@savon-noir @Dutchy- @bmx0r - any updates on this?

**Comment by Dutchy-** [comment]
I don't understand why I was mentioned here

**Comment by savon-noir** [comment]
Thanks for submitting and sorry for the delay in the response.  I'm currently in a clean-up exercise of the code.Thanks for proposing a fix. Although, I'd want to adapt a bit the proposed fix since, I want to provide a library without mandatory dependencies. As the defusexml seems to "just" monkey patch the calls, i would simply push it as a preferred parser like its done for enabling cElementTree without enforcing it. Also, I'd like to have some test samples to validate parsing unittests with both libs. Will have a look at all this. Thanks for the proposal.

**Comment by savon-noir** [comment]
superseeded by  PR #107 (included in PR #109)

**Pull request closed without merging**
