### PR TITLE
Small fixes

### LINKED ISSUE #72: extraports_reasons None.get
If extraports exists, r becomes None. r.get raises an exception.

### PR DESCRIPTION
**Pull request by Deedasmi**
Couple small fixes for issues I've opened

### CODE REVIEW

**Comment by savon-noir** [comment]
Hello, 

thanks for your pull request. Change make travis job fail. Could you please adapt your pull req and I'll merge it in the master branch. You apparently inserted a whitespace on line 469. Make sure to clean it to have a pep8 compliant code please. 

See error below from travis:

./libnmap/objects/host.py:469:1: W293 blank line contains whitespace
./build/lib/libnmap/objects/host.py:469:1: W293 blank line contains whitespace
The command "pep8 . --exclude test,docs,examples" failed and exited with 1 during .
Your build has been stopped.

**Comment by Deedasmi** [comment]
Sorry about that.

**Comment by farhaven** [comment]
Is there an option to get this pull request merged and a new release made? I can work around this in local code but I'd prefer a non-monkey-patched upstream fix :)

**Comment by savon-noir** [comment]
thanks for the pull request @Deedasmi  and thanks for the reminder @farhaven finally merged back in upstream. I should really spend some time in libnmap and give it some love.

**Pull request merged**
