### PR TITLE
remove multiprocessing from libnmap/process.py

### PR DESCRIPTION
**Pull request by pyoner**
for https://github.com/savon-noir/python-libnmap/issues/48

### CODE REVIEW

**Comment by savon-noir** [comment]
i'll do some testing of your proposal. thanks for submiting and pull requesting

**Comment by pyoner** [comment]
any news?

**Comment by aphillipo** [comment]
It would be lovely if this was merged as without it I get an error from the multiprocessing module using this library from celery.  Thanks.

**Comment by savon-noir** [comment]
hello, thanks for pushing up. i've been quite busy these days. i'm thinking of a rewrite of process.py based on your pull request.

within 2 weeks most probably.

**Comment by savon-noir** [comment]
Hello,

I reviewed finally reviewed your proposal. I was quite short of time lately...

I'll merge it. Will correct two other bugs and then update on pypi as version 0.7.

Thanks for your contribution.

Ronald

**Pull request merged**
